### ISSUE TITLE
dev dependency to gulp while used in production

### ISSUE THREAD

**Issue by yoann-antoviaque** [OverZealous/gulp-task-listing#10]
line 6 of index.js we have a require('gulp')
but gulp is listed as a devDependency

If i am not mistaken, it should be a production dependency

**Comment by OverZealous** [comment]
Nope.  You should be depending on the library in your code, it's only needed directly within the library during testing.

If we included our own copy of Gulp, it would break the way this works.

**Comment by anouar-hamed** [comment]
i think that there's a dependency problem. im having this error:
Error: Cannot find module 'gulp'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/anouar/node_modules/Test-gulp-task-listing/gulp-task-listing/index.js:6:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)



you can see it on this project after:
> npm install
> gulp

[Test-gulp-task-listing.zip](https://github.com/OverZealous/gulp-task-listing/files/145073/Test-gulp-task-listing.zip)
